#!/bin/bash
# Lint the wiki: find broken links, orphan pages, missing pages, contradictions.
# Writes a report to wiki/_health.md and exits 0 (or 1 if broken links found).
set -euo pipefail

KB_ROOT="$(cd "$(dirname "$0")/.." && pwd)"

KB_ROOT="$KB_ROOT" python3 << 'PYEOF'
import os, re, sys
from collections import defaultdict
from datetime import datetime

kb_root = os.environ['KB_ROOT']
wiki_dir = os.path.join(kb_root, "wiki")

# Collect all wiki pages
all_pages = set()
page_paths = {}
for root, dirs, files in os.walk(wiki_dir):
    for f in files:
        if f.endswith(".md") and f != ".gitkeep" and f != "_health.md":
            page_name = f[:-3]
            all_pages.add(page_name)
            page_paths[page_name] = os.path.join(root, f)

# Parse wikilinks (handle |alias and #section syntax)
link_pattern = re.compile(r'\[\[([^\]|#]+?)(#[^\]|]*)?(\|[^\]]+)?\]\]')

links_from = defaultdict(set)
links_to = defaultdict(set)
broken_links = defaultdict(set)

for page, filepath in page_paths.items():
    with open(filepath) as f:
        content = f.read()
    for match in link_pattern.finditer(content):
        target = match.group(1).strip()
        target_base = target.split('/')[-1]
        if target in all_pages:
            links_from[page].add(target)
            links_to[target].add(page)
        elif target_base in all_pages:
            links_from[page].add(target_base)
            links_to[target_base].add(page)
        else:
            broken_links[page].add(target)

# Orphan check (excluding meta pages)
exclude_orphan = {'index', 'log', 'overview', 'hot', '_health'}
orphans = sorted([p for p in all_pages if p not in exclude_orphan and not links_to.get(p)])

# Stats
total_links = sum(len(s) for s in links_from.values())
total_broken = sum(len(s) for s in broken_links.values())

# Top inbound (most-linked) pages
top_linked = sorted(links_to.items(), key=lambda x: -len(x[1]))[:10]

# Build report
now = datetime.now().strftime('%Y-%m-%d %H:%M')
report = f"""---
type: health
updated: {datetime.now().strftime('%Y-%m-%d')}
---

# Wiki Health Report

_Auto-generated by `scripts/lint-wiki.sh`. Last run: **{now}**._

## Summary

| Metric | Value |
|--------|-------|
| Total wiki pages | {len(all_pages)} |
| Total wikilinks | {total_links} |
| Broken links | **{total_broken}** |
| Orphan pages | **{len(orphans)}** |
| Pages with outbound links | {len(links_from)} |

"""

if total_broken > 0:
    report += "## Broken Wikilinks\n\nThese references point to pages that don't exist. Either fix the link or create the page.\n\n"
    for page, targets in sorted(broken_links.items()):
        for t in sorted(targets):
            report += f"- `{page}` → `[[{t}]]`\n"
    report += "\n"
else:
    report += "## Broken Wikilinks\n\nNone. All wikilinks resolve.\n\n"

if orphans:
    report += "## Orphan Pages\n\nThese pages exist but no other page links to them. Either add inbound links, integrate them into the index, or remove them.\n\n"
    for o in orphans:
        report += f"- [[{o}]]\n"
    report += "\n"
else:
    report += "## Orphan Pages\n\nNone. Every page has at least one inbound link.\n\n"

report += "## Most-Linked Pages (Top 10)\n\nThese are the central hubs of the wiki, pages with the most incoming references.\n\n"
for page, linkers in top_linked:
    report += f"- [[{page}]], {len(linkers)} inbound link{'s' if len(linkers) != 1 else ''}\n"

# Pages by category
by_cat = defaultdict(int)
for fp in page_paths.values():
    rel = os.path.relpath(fp, wiki_dir)
    cat = rel.split(os.sep)[0] if os.sep in rel else 'root'
    by_cat[cat] += 1

report += "\n## Pages by Category\n\n"
for cat, count in sorted(by_cat.items()):
    report += f"- `{cat}/`: {count} pages\n"

# Write report
out_path = os.path.join(wiki_dir, "_health.md")
with open(out_path, "w") as f:
    f.write(report)

# Console summary
print(f"Wiki health report written to wiki/_health.md")
print(f"  Total pages: {len(all_pages)}")
print(f"  Broken links: {total_broken}")
print(f"  Orphan pages: {len(orphans)}")

# Exit code based on broken links
sys.exit(1 if total_broken > 0 else 0)
PYEOF
